### PR TITLE
Extend max length from 120 to 150.  

### PR DESCRIPTION
**Pull request by NicholasTuck**
120 gets hit often and is not a problem. Trev mentioned trying 150, so trying that, and we can assess if it should be more or less over time.

GC-1885

### CODE REVIEW

**Comment by banderson623** [comment]
honestly, just drop this length limit entirely. Especially if we have the appetite to change it.

**Comment by ztoben** [comment]
My vote is turn it off entirely and then also mass remove any instances we ignore it at a line or file level all in this PR.

**Comment by trevtrich** [comment]
i'm alright with this since it sounds like i'm the only one that likes it 😄  but this means we shouldn't see any PRs with comments that say "you shoudl break this up into multiples lines to make it more readable"

**Review by trevtrich — COMMENTED** [review]
the hive mind has spoken. lets :ax

**Comment by NicholasTuck** [comment]
> i'm alright with this since it sounds like i'm the only one that likes it 😄 but this means we shouldn't see any PRs with comments that say "you shoudl break this up into multiples lines to make it more readable"

😁 😁  I'm with you. No hateful overly syntax focused PRs.  Code formatting rules I think should be circumstantial and brought up in a PR when is of substantial impact. But they shouldn't be mentioned as a rule like a computer would, I agree. An extra space here, a missing space here, a long line here, wtv, ignore it, clean it up if you're in that code who cares.  

I think sometimes a line that's 20chars long could be asked to be split up, if it's like 3 function calls all in one line, it may just be hard to read still, and I'd be down to receive that feedback.

**Comment by banderson623** [comment]
While I gave my opinion on this, I am 100% indifferent on what is best for the team. My role is hardly to write code, and I was probably to quick with my opinion above.

So whatever the team decides is fine with me.

**Pull request merged**
